### ISSUE TITLE
beklenti

### ISSUE THREAD

**Issue by kamilklkn** [sahibinden/sahibinden.github.io#55]
Yaklaşık olarak  bir yıl önce proje ile tanışmıştım. Yazılarınız ümit vericiydi ama şimdi bakıyorumda kimse yazmıyor. Bu issu belki sizi tekrar yazmaya teşfik eder.

**Comment by sercaneraslan** [comment]
Selam Kamil,

Desteğin için teşekkürler, ekip arkadaşlarımı konudan haberdar ettim.

Tekrar teşekkürler.
Sercan
